# Generated by Django 5.x on 2026-02-11
import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('auth_provider', models.CharField(choices=[('email', 'email'), ('google', 'google'), ('apple', 'apple')], max_length=20)),
                ('provider_id', models.TextField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('manager', 'manager')], default='user', max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('blocked', 'blocked'), ('deleted', 'deleted')], db_index=True, default='active', max_length=20)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('closed', 'closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'support_tickets',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tracks',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_token', models.TextField(unique=True)),
                ('platform', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=20)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'user_devices',
                'indexes': [models.Index(fields=['user'], name='user_devices_user_id_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('display_name', models.CharField(max_length=150)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('playback_speed', models.FloatField(default=1.0)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('silent_mode', models.BooleanField(default=False)),
                ('dark_mode', models.BooleanField(default=True)),
                ('auto_play_next', models.BooleanField(default=True)),
                ('download_over_wifi_only', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('razorpay', 'razorpay'), ('apple_iap', 'apple_iap'), ('google_iap', 'google_iap')], max_length=20)),
                ('status', models.CharField(choices=[('trial', 'trial'), ('active', 'active'), ('expired', 'expired'), ('cancelled', 'cancelled')], db_index=True, max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'subscriptions',
                'indexes': [models.Index(fields=['user'], name='subscriptions_user_id_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=10)),
                ('message', models.TextField()),
                ('attachment_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supportticket')),
            ],
            options={
                'db_table': 'support_messages',
            },
        ),
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('played_seconds', models.IntegerField()),
                ('total_duration', models.IntegerField()),
                ('completion_percentage', models.FloatField()),
                ('source', models.CharField(choices=[('home', 'home'), ('search', 'search'), ('playlist', 'playlist'), ('recommended', 'recommended')], max_length=20)),
                ('device_platform', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'play_events',
                'indexes': [
                    models.Index(fields=['user'], name='play_events_user_id_idx'),
                    models.Index(fields=['track'], name='play_events_track_id_idx'),
                    models.Index(fields=['created_at'], name='play_events_created_at_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('normalized_query', models.TextField()),
                ('result_count', models.IntegerField()),
                ('source_screen', models.CharField(choices=[('home', 'home'), ('search_page', 'search_page')], max_length=20)),
                ('device_platform', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'search_logs',
                'indexes': [
                    models.Index(fields=['normalized_query'], name='search_logs_normalized_query_idx'),
                    models.Index(fields=['created_at'], name='search_logs_created_at_idx'),
                ],
            },
        ),
    ]