# Generated by Django 5.x on 2026-02-11
import django.db.models.deletion
import django.utils.timezone
import uuid

from django.db import migrations, models


def backfill_track_required_fields(apps, schema_editor):
    Track = apps.get_model('api', 'Track')
    now = django.utils.timezone.now()

    Track.objects.filter(title__isnull=True).update(title='Untitled track')
    Track.objects.filter(title='').update(title='Untitled track')

    Track.objects.filter(audio_url__isnull=True).update(audio_url='')
    Track.objects.filter(audio_url='').update(audio_url='')

    Track.objects.filter(speaker_name__isnull=True).update(speaker_name='Unknown speaker')
    Track.objects.filter(speaker_name='').update(speaker_name='Unknown speaker')

    Track.objects.filter(duration_seconds__isnull=True).update(duration_seconds=0)
    Track.objects.filter(updated_at__isnull=True).update(updated_at=now)


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='track',
            name='audio_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tracks', to='api.user'),
        ),
        migrations.AddField(
            model_name='track',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='track',
            name='speaker_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('archived', 'archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='visibility',
            field=models.CharField(choices=[('public', 'public'), ('hidden', 'hidden')], default='public', max_length=20),
        ),
        migrations.RunPython(backfill_track_required_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='speaker_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration_seconds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='track',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
