# Generated by Django 5.x on 2026-02-11
import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_expand_tracks_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image_url', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('premium', 'premium'), ('hidden', 'hidden')], default='public', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists_created', to='api.user')),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
    ]
