# Generated by Django 5.x on 2026-02-11
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_create_playlists'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['visibility'], name='idx_playlists_visibility'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['created_at'], name='idx_playlists_created_at'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['is_active'], name='idx_playlists_active'),
        ),
    ]
