# Generated by Django 5.x on 2026-02-11
import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_add_playlist_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.track')),
            ],
            options={
                'db_table': 'playlist_tracks',
            },
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('playlist', 'track'), name='uq_playlist_tracks_playlist_track'),
        ),
        migrations.AddConstraint(
            model_name='playlisttrack',
            constraint=models.UniqueConstraint(fields=('playlist', 'position'), name='uq_playlist_tracks_playlist_position'),
        ),
        migrations.AddIndex(
            model_name='playlisttrack',
            index=models.Index(fields=['playlist'], name='idx_playlist_tracks_playlist'),
        ),
        migrations.AddIndex(
            model_name='playlisttrack',
            index=models.Index(fields=['track'], name='idx_playlist_tracks_track'),
        ),
    ]
