# Generated by Django 5.x on 2026-02-11
import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_create_playlist_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists_created', to='api.user'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.CheckConstraint(condition=models.Q(visibility__in=['public', 'premium', 'hidden']), name='chk_playlist_visibility'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(condition=models.Q(deleted_at__isnull=True), fields=['id'], name='idx_playlists_active_only'),
        ),
    ]
