# Generated by Django 5.x on 2026-02-11
import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_harden_playlist_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('free_trial_days', models.IntegerField(default=0)),
                ('auto_lock_new_content', models.BooleanField(default=False)),
                ('allow_gifting', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_settings_updates', to='api.user')),
            ],
            options={
                'db_table': 'premium_settings',
            },
        ),
    ]
