# Generated by Django 5.x on 2026-02-11
from django.db import migrations, models


def validate_singleton_premium_settings(apps, schema_editor):
    PremiumSettings = apps.get_model('api', 'PremiumSettings')
    if PremiumSettings.objects.count() > 1:
        raise RuntimeError(
            'premium_settings contains multiple rows; clean up to one row before applying singleton enforcement.'
        )


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_create_premium_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsettings',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
        migrations.RunPython(validate_singleton_premium_settings, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='premiumsettings',
            constraint=models.CheckConstraint(condition=models.Q(singleton_key=1), name='chk_premium_settings_singleton_key'),
        ),
    ]
