# Generated by Django 5.x on 2026-02-11
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_enforce_singleton_premium_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendation_rules',
            },
        ),
        migrations.AddIndex(
            model_name='recommendationrule',
            index=models.Index(fields=['is_active', 'priority'], name='idx_reco_rules_active_priority'),
        ),
    ]
