# Generated by Django 5.x on 2026-02-11
import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0009_create_recommendation_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('platform_visible', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_public_signup', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('allow_guest_access', models.BooleanField(default=False)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_push_notifications', models.BooleanField(default=True)),
                ('email_provider_config', models.JSONField(blank=True, null=True)),
                ('push_provider_config', models.JSONField(blank=True, null=True)),
                ('default_track_visibility', models.CharField(choices=[('public', 'public'), ('premium', 'premium')], default='public', max_length=20)),
                ('max_upload_size_mb', models.PositiveIntegerField(default=100)),
                ('allowed_audio_formats', models.JSONField(blank=True, default=list)),
                ('max_login_attempts', models.PositiveSmallIntegerField(default=5)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('password_policy', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_settings_updates', to='api.user')),
            ],
            options={
                'db_table': 'platform_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='platformsettings',
            constraint=models.CheckConstraint(condition=models.Q(singleton_key=1), name='chk_platform_settings_singleton_key'),
        ),
    ]
