# Generated by Django 5.x on 2026-02-11
import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_create_admin_audit_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.track')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'user_downloads',
            },
        ),
        migrations.AddConstraint(
            model_name='userdownload',
            constraint=models.UniqueConstraint(fields=('user', 'track', 'device_id'), name='uq_user_downloads_user_track_device'),
        ),
    ]
