# Generated by Django 5.2.11 on 2026-02-12 21:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_create_user_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackCoverImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'track_cover_images',
            },
        ),
        migrations.AddField(
            model_name='trackcoverimage',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='api.track'),
        ),
        migrations.AddIndex(
            model_name='trackcoverimage',
            index=models.Index(fields=['track', 'position'], name='idx_track_covimg_track_pos'),
        ),
        migrations.AddConstraint(
            model_name='trackcoverimage',
            constraint=models.UniqueConstraint(fields=('track', 'position'), name='uq_track_covimg_track_pos'),
        ),
    ]
