# Generated by Codex on 2026-02-12

from django.db import migrations


def seed_default_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    for category_name in ['Song', 'Podcast']:
        Category.objects.get_or_create(name=category_name)


def unseed_default_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    Category.objects.filter(name__in=['Song', 'Podcast']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_trackcoverimage_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_default_categories, unseed_default_categories),
    ]
