# Generated by Django 5.x on 2026-02-13
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0017_seed_platform_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=64, unique=True)),
                ('refresh_token', models.CharField(max_length=64, unique=True)),
                ('access_expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to='api.user')),
            ],
            options={
                'db_table': 'admin_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['access_token'], name='idx_admin_sessions_access'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['refresh_token'], name='idx_admin_sessions_refresh'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['user'], name='idx_admin_sessions_user'),
        ),
    ]
