# Generated by Django 5.2.11 on 2026-02-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_usernotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='analytics_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='personalization_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
