# Generated by Django 5.2.11 on 2026-02-23 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_play_events_user_id_idx_play_events_user_id_3b5c24_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMfaBackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.TextField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_mfa_backup_codes',
            },
        ),
        migrations.CreateModel(
            name='UserMfaTotp',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mfa_totp', serialize=False, to='api.user')),
                ('secret', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_mfa_totp',
            },
        ),
        migrations.AddField(
            model_name='usermfabackupcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='usermfabackupcode',
            index=models.Index(fields=['user', 'used_at'], name='idx_mfa_backup_user_used'),
        ),
    ]
