# Generated by Django 5.2.11 on 2026-02-25

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_support_chat_v1_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrackLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by_users', to='api.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_tracks', to='api.user')),
            ],
            options={
                'db_table': 'user_liked_tracks',
            },
        ),
        migrations.AddConstraint(
            model_name='usertracklike',
            constraint=models.UniqueConstraint(fields=('user', 'track'), name='uq_ulikes_user_track'),
        ),
        migrations.AddIndex(
            model_name='usertracklike',
            index=models.Index(fields=['user', 'created_at'], name='idx_ulikes_user_created'),
        ),
        migrations.AddIndex(
            model_name='usertracklike',
            index=models.Index(fields=['track'], name='idx_ulikes_track'),
        ),
    ]
