# Generated by Django 5.2.11 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_create_user_track_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='display_advertisement',
            field=models.BooleanField(default=False),
        ),
    ]
